//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package org.purl.net.mlo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.purl.dc.elements._1.SimpleLiteral;


/**
 * <p>Java class for LearningOpportunitySpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LearningOpportunitySpecification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://purl.org/net/mlo}LearningOpportunityObject">
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.org/net/mlo}qualification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}credit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}level" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}specifies" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearningOpportunitySpecification", propOrder = {
    "qualification",
    "credit",
    "level",
    "specifies"
})
public class LearningOpportunitySpecification
    extends LearningOpportunityObject
{

    protected List<QualificationDType> qualification;
    protected List<CreditDType> credit;
    protected List<SimpleLiteral> level;
    protected List<Association> specifies;

    /**
     * Gets the value of the qualification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationDType }
     * 
     * 
     */
    public List<QualificationDType> getQualification() {
        if (qualification == null) {
            qualification = new ArrayList<QualificationDType>();
        }
        return this.qualification;
    }

    /**
     * Gets the value of the credit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the credit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCredit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditDType }
     * 
     * 
     */
    public List<CreditDType> getCredit() {
        if (credit == null) {
            credit = new ArrayList<CreditDType>();
        }
        return this.credit;
    }

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getLevel() {
        if (level == null) {
            level = new ArrayList<SimpleLiteral>();
        }
        return this.level;
    }

    /**
     * Gets the value of the specifies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specifies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecifies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Association }
     * 
     * 
     */
    public List<Association> getSpecifies() {
        if (specifies == null) {
            specifies = new ArrayList<Association>();
        }
        return this.specifies;
    }

}
