//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package org.purl.net.mlo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.purl.dc.elements._1.SimpleLiteral;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.purl.net.mlo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Specifies_QNAME = new QName("http://purl.org/net/mlo", "specifies");
    private final static QName _Offers_QNAME = new QName("http://purl.org/net/mlo", "offers");
    private final static QName _Postcode_QNAME = new QName("http://purl.org/net/mlo", "postcode");
    private final static QName _Prerequisite_QNAME = new QName("http://purl.org/net/mlo", "prerequisite");
    private final static QName _Start_QNAME = new QName("http://purl.org/net/mlo", "start");
    private final static QName _LearningOpportunityInstance_QNAME = new QName("http://purl.org/net/mlo", "learningOpportunityInstance");
    private final static QName _OfferedAt_QNAME = new QName("http://purl.org/net/mlo", "offeredAt");
    private final static QName _Street_QNAME = new QName("http://purl.org/net/mlo", "street");
    private final static QName _HasPart_QNAME = new QName("http://purl.org/net/mlo", "hasPart");
    private final static QName _Duration_QNAME = new QName("http://purl.org/net/mlo", "duration");
    private final static QName _Address_QNAME = new QName("http://purl.org/net/mlo", "address");
    private final static QName _LearningOpportunityProvider_QNAME = new QName("http://purl.org/net/mlo", "learningOpportunityProvider");
    private final static QName _Assessment_QNAME = new QName("http://purl.org/net/mlo", "assessment");
    private final static QName _LanguageOfInstruction_QNAME = new QName("http://purl.org/net/mlo", "languageOfInstruction");
    private final static QName _LearningOpportunitySpecification_QNAME = new QName("http://purl.org/net/mlo", "learningOpportunitySpecification");
    private final static QName _Objective_QNAME = new QName("http://purl.org/net/mlo", "objective");
    private final static QName _Fax_QNAME = new QName("http://purl.org/net/mlo", "fax");
    private final static QName _Places_QNAME = new QName("http://purl.org/net/mlo", "places");
    private final static QName _Cost_QNAME = new QName("http://purl.org/net/mlo", "cost");
    private final static QName _Url_QNAME = new QName("http://purl.org/net/mlo", "url");
    private final static QName _Email_QNAME = new QName("http://purl.org/net/mlo", "email");
    private final static QName _Town_QNAME = new QName("http://purl.org/net/mlo", "town");
    private final static QName _IsPartOf_QNAME = new QName("http://purl.org/net/mlo", "isPartOf");
    private final static QName _Engagement_QNAME = new QName("http://purl.org/net/mlo", "engagement");
    private final static QName _Phone_QNAME = new QName("http://purl.org/net/mlo", "phone");
    private final static QName _Location_QNAME = new QName("http://purl.org/net/mlo", "location");
    private final static QName _Level_QNAME = new QName("http://purl.org/net/mlo", "level");
    private final static QName _Qualification_QNAME = new QName("http://purl.org/net/mlo", "qualification");
    private final static QName _Credit_QNAME = new QName("http://purl.org/net/mlo", "credit");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.purl.net.mlo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OriginalCreditDType }
     * 
     */
    public OriginalCreditDType createOriginalCreditDType() {
        return new OriginalCreditDType();
    }

    /**
     * Create an instance of {@link OriginalStartDType }
     * 
     */
    public OriginalStartDType createOriginalStartDType() {
        return new OriginalStartDType();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link OriginalLocationDType }
     * 
     */
    public OriginalLocationDType createOriginalLocationDType() {
        return new OriginalLocationDType();
    }

    /**
     * Create an instance of {@link VocabularyDType }
     * 
     */
    public VocabularyDType createVocabularyDType() {
        return new VocabularyDType();
    }

    /**
     * Create an instance of {@link LocationDType }
     * 
     */
    public LocationDType createLocationDType() {
        return new LocationDType();
    }

    /**
     * Create an instance of {@link LearningOpportunitySpecification }
     * 
     */
    public LearningOpportunitySpecification createLearningOpportunitySpecification() {
        return new LearningOpportunitySpecification();
    }

    /**
     * Create an instance of {@link OriginalQualificationDType }
     * 
     */
    public OriginalQualificationDType createOriginalQualificationDType() {
        return new OriginalQualificationDType();
    }

    /**
     * Create an instance of {@link AssessmentDType }
     * 
     */
    public AssessmentDType createAssessmentDType() {
        return new AssessmentDType();
    }

    /**
     * Create an instance of {@link OriginalDurationDType }
     * 
     */
    public OriginalDurationDType createOriginalDurationDType() {
        return new OriginalDurationDType();
    }

    /**
     * Create an instance of {@link DurationDType }
     * 
     */
    public DurationDType createDurationDType() {
        return new DurationDType();
    }

    /**
     * Create an instance of {@link ObjectiveDType }
     * 
     */
    public ObjectiveDType createObjectiveDType() {
        return new ObjectiveDType();
    }

    /**
     * Create an instance of {@link CreditDType }
     * 
     */
    public CreditDType createCreditDType() {
        return new CreditDType();
    }

    /**
     * Create an instance of {@link LearningOpportunityInstance }
     * 
     */
    public LearningOpportunityInstance createLearningOpportunityInstance() {
        return new LearningOpportunityInstance();
    }

    /**
     * Create an instance of {@link PrerequisiteDType }
     * 
     */
    public PrerequisiteDType createPrerequisiteDType() {
        return new PrerequisiteDType();
    }

    /**
     * Create an instance of {@link TemporalDType }
     * 
     */
    public TemporalDType createTemporalDType() {
        return new TemporalDType();
    }

    /**
     * Create an instance of {@link QualificationDType }
     * 
     */
    public QualificationDType createQualificationDType() {
        return new QualificationDType();
    }

    /**
     * Create an instance of {@link LearningOpportunityProvider }
     * 
     */
    public LearningOpportunityProvider createLearningOpportunityProvider() {
        return new LearningOpportunityProvider();
    }

    /**
     * Create an instance of {@link StartDType }
     * 
     */
    public StartDType createStartDType() {
        return new StartDType();
    }

    /**
     * Create an instance of {@link DescriptionDType }
     * 
     */
    public DescriptionDType createDescriptionDType() {
        return new DescriptionDType();
    }

    /**
     * Create an instance of {@link SubjectDType }
     * 
     */
    public SubjectDType createSubjectDType() {
        return new SubjectDType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "specifies")
    public JAXBElement<Association> createSpecifies(Association value) {
        return new JAXBElement<Association>(_Specifies_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "offers")
    public JAXBElement<Association> createOffers(Association value) {
        return new JAXBElement<Association>(_Offers_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "postcode")
    public JAXBElement<String> createPostcode(String value) {
        return new JAXBElement<String>(_Postcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrerequisiteDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "prerequisite")
    public JAXBElement<PrerequisiteDType> createPrerequisite(PrerequisiteDType value) {
        return new JAXBElement<PrerequisiteDType>(_Prerequisite_QNAME, PrerequisiteDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "start")
    public JAXBElement<StartDType> createStart(StartDType value) {
        return new JAXBElement<StartDType>(_Start_QNAME, StartDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningOpportunityInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "learningOpportunityInstance")
    public JAXBElement<LearningOpportunityInstance> createLearningOpportunityInstance(LearningOpportunityInstance value) {
        return new JAXBElement<LearningOpportunityInstance>(_LearningOpportunityInstance_QNAME, LearningOpportunityInstance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "offeredAt")
    public JAXBElement<Association> createOfferedAt(Association value) {
        return new JAXBElement<Association>(_OfferedAt_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "hasPart")
    public JAXBElement<Association> createHasPart(Association value) {
        return new JAXBElement<Association>(_HasPart_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "duration")
    public JAXBElement<DurationDType> createDuration(DurationDType value) {
        return new JAXBElement<DurationDType>(_Duration_QNAME, DurationDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningOpportunityProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "learningOpportunityProvider")
    public JAXBElement<LearningOpportunityProvider> createLearningOpportunityProvider(LearningOpportunityProvider value) {
        return new JAXBElement<LearningOpportunityProvider>(_LearningOpportunityProvider_QNAME, LearningOpportunityProvider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssessmentDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "assessment")
    public JAXBElement<AssessmentDType> createAssessment(AssessmentDType value) {
        return new JAXBElement<AssessmentDType>(_Assessment_QNAME, AssessmentDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "languageOfInstruction")
    public JAXBElement<SimpleLiteral> createLanguageOfInstruction(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_LanguageOfInstruction_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningOpportunitySpecification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "learningOpportunitySpecification")
    public JAXBElement<LearningOpportunitySpecification> createLearningOpportunitySpecification(LearningOpportunitySpecification value) {
        return new JAXBElement<LearningOpportunitySpecification>(_LearningOpportunitySpecification_QNAME, LearningOpportunitySpecification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectiveDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "objective")
    public JAXBElement<ObjectiveDType> createObjective(ObjectiveDType value) {
        return new JAXBElement<ObjectiveDType>(_Objective_QNAME, ObjectiveDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "places")
    public JAXBElement<Resource> createPlaces(Resource value) {
        return new JAXBElement<Resource>(_Places_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "cost")
    public JAXBElement<SimpleLiteral> createCost(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Cost_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "url")
    public JAXBElement<SimpleLiteral> createUrl(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Url_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "town")
    public JAXBElement<String> createTown(String value) {
        return new JAXBElement<String>(_Town_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "isPartOf")
    public JAXBElement<Association> createIsPartOf(Association value) {
        return new JAXBElement<Association>(_IsPartOf_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "engagement")
    public JAXBElement<SimpleLiteral> createEngagement(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Engagement_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "location")
    public JAXBElement<LocationDType> createLocation(LocationDType value) {
        return new JAXBElement<LocationDType>(_Location_QNAME, LocationDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "level")
    public JAXBElement<SimpleLiteral> createLevel(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Level_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualificationDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "qualification")
    public JAXBElement<QualificationDType> createQualification(QualificationDType value) {
        return new JAXBElement<QualificationDType>(_Qualification_QNAME, QualificationDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreditDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/mlo", name = "credit")
    public JAXBElement<CreditDType> createCredit(CreditDType value) {
        return new JAXBElement<CreditDType>(_Credit_QNAME, CreditDType.class, null, value);
    }

}
