//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 04:17:50 PM BST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/net/mlo",
xmlns = {
    @XmlNs(namespaceURI = "http://purl.org/net/mlo", prefix = "mlo"),
    @XmlNs(namespaceURI = "http://purl.org/net/cm", prefix = "credit")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.purl.net.mlo;

import javax.xml.bind.annotation.XmlNs;
