//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package org.purl.net.mlo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.purl.dc.elements._1.DescriptionDType;
import org.purl.dc.elements._1.SimpleLiteral;


/**
 * <p>Java class for qualificationDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qualificationDType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://purl.org/net/mlo}qualificationDType">
 *       &lt;redefine>
 *         &lt;complexType name="qualificationDType">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://xcri.org/profiles/1.2/catalog}abbr" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/terms/}educationLevel" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}type" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}url" minOccurs="0"/>
 *         &lt;element ref="{http://xcri.org/profiles/1.2/catalog}awardedBy" minOccurs="0"/>
 *         &lt;element ref="{http://xcri.org/profiles/1.2/catalog}accreditedBy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qualificationDType", propOrder = {
    "identifier",
    "title",
    "abbr",
    "description",
    "educationLevel",
    "type",
    "url",
    "awardedBy",
    "accreditedBy"
})
public class QualificationDType
    extends OriginalQualificationDType implements java.io.Serializable
{

    @XmlElementRef(name = "identifier", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    protected List<JAXBElement<SimpleLiteral>> identifier;
    @XmlElementRef(name = "title", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    protected List<JAXBElement<SimpleLiteral>> title;
    @XmlElement(namespace = "http://xcri.org/profiles/1.2/catalog")
    protected String abbr;
    @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    protected List<JAXBElement<DescriptionDType>> description;
    @XmlElement(namespace = "http://purl.org/dc/terms/")
    protected SimpleLiteral educationLevel;
    @XmlElementRef(name = "type", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    protected JAXBElement<SimpleLiteral> type;
    protected SimpleLiteral url;
    @XmlElement(namespace = "http://xcri.org/profiles/1.2/catalog")
    protected String awardedBy;
    @XmlElement(namespace = "http://xcri.org/profiles/1.2/catalog")
    protected String accreditedBy;

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * 
     */
    public List<JAXBElement<SimpleLiteral>> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<JAXBElement<SimpleLiteral>>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * 
     */
    public List<JAXBElement<SimpleLiteral>> getTitle() {
        if (title == null) {
            title = new ArrayList<JAXBElement<SimpleLiteral>>();
        }
        return this.title;
    }

    /**
     * Gets the value of the abbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * Sets the value of the abbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr(String value) {
        this.abbr = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DescriptionDType }{@code >}
     * {@link JAXBElement }{@code <}{@link DescriptionDType }{@code >}
     * {@link JAXBElement }{@code <}{@link DescriptionDType }{@code >}
     * {@link JAXBElement }{@code <}{@link DescriptionDType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<DescriptionDType>> getDescription() {
        if (description == null) {
            description = new ArrayList<JAXBElement<DescriptionDType>>();
        }
        return this.description;
    }

    /**
     * Gets the value of the educationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getEducationLevel() {
        return educationLevel;
    }

    /**
     * Sets the value of the educationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setEducationLevel(SimpleLiteral value) {
        this.educationLevel = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    public JAXBElement<SimpleLiteral> getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     *     
     */
    public void setType(JAXBElement<SimpleLiteral> value) {
        this.type = ((JAXBElement<SimpleLiteral> ) value);
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setUrl(SimpleLiteral value) {
        this.url = value;
    }

    /**
     * Gets the value of the awardedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardedBy() {
        return awardedBy;
    }

    /**
     * Sets the value of the awardedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardedBy(String value) {
        this.awardedBy = value;
    }

    /**
     * Gets the value of the accreditedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccreditedBy() {
        return accreditedBy;
    }

    /**
     * Sets the value of the accreditedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccreditedBy(String value) {
        this.accreditedBy = value;
    }

}
