//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 04:17:50 PM BST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1999/xhtml",
xmlns = {
    @XmlNs(namespaceURI = "http://www.w3.org/1999/xhtml", prefix = "xhtml")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.w3._1999.xhtml;

import javax.xml.bind.annotation.XmlNs;

