//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 09:03:32 AM BST 
//


package org.xcri.profiles._1_2.catalog.terms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xcri.profiles._1_2.catalog.terms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xcri.profiles._1_2.catalog.terms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContactPattern }
     * 
     */
    public ContactPattern createContactPattern() {
        return new ContactPattern();
    }

    /**
     * Create an instance of {@link CareerOutcome }
     * 
     */
    public CareerOutcome createCareerOutcome() {
        return new CareerOutcome();
    }

    /**
     * Create an instance of {@link LeadsTo }
     * 
     */
    public LeadsTo createLeadsTo() {
        return new LeadsTo();
    }

    /**
     * Create an instance of {@link TeachingStrategy }
     * 
     */
    public TeachingStrategy createTeachingStrategy() {
        return new TeachingStrategy();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link ProvidedResource }
     * 
     */
    public ProvidedResource createProvidedResource() {
        return new ProvidedResource();
    }

    /**
     * Create an instance of {@link SpecialFeature }
     * 
     */
    public SpecialFeature createSpecialFeature() {
        return new SpecialFeature();
    }

    /**
     * Create an instance of {@link StudyHours }
     * 
     */
    public StudyHours createStudyHours() {
        return new StudyHours();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Support }
     * 
     */
    public Support createSupport() {
        return new Support();
    }

    /**
     * Create an instance of {@link IndicativeResource }
     * 
     */
    public IndicativeResource createIndicativeResource() {
        return new IndicativeResource();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Structure }
     * 
     */
    public Structure createStructure() {
        return new Structure();
    }

    /**
     * Create an instance of {@link RequiredResource }
     * 
     */
    public RequiredResource createRequiredResource() {
        return new RequiredResource();
    }

    /**
     * Create an instance of {@link ContactHours }
     * 
     */
    public ContactHours createContactHours() {
        return new ContactHours();
    }

}
