//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 09:03:32 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xcri.org/profiles/1.2/catalog/terms")
package org.xcri.profiles._1_2.catalog.terms;
