//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package uk.co.xcri;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.xcri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.xcri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CourseTypeCPD }
     * 
     */
    public CourseTypeCPD createCourseTypeCPD() {
        return new CourseTypeCPD();
    }

    /**
     * Create an instance of {@link Ukprn }
     * 
     */
    public Ukprn createUkprn() {
        return new Ukprn();
    }

    /**
     * Create an instance of {@link UcasInstCode }
     * 
     */
    public UcasInstCode createUcasInstCode() {
        return new UcasInstCode();
    }

    /**
     * Create an instance of {@link TargetAudience }
     * 
     */
    public TargetAudience createTargetAudience() {
        return new TargetAudience();
    }

    /**
     * Create an instance of {@link SSAC2001 }
     * 
     */
    public SSAC2001 createSSAC2001() {
        return new SSAC2001();
    }

    /**
     * Create an instance of {@link ProfessionalStatus }
     * 
     */
    public ProfessionalStatus createProfessionalStatus() {
        return new ProfessionalStatus();
    }

    /**
     * Create an instance of {@link UcasCode }
     * 
     */
    public UcasCode createUcasCode() {
        return new UcasCode();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link InternalID }
     * 
     */
    public InternalID createInternalID() {
        return new InternalID();
    }

    /**
     * Create an instance of {@link CourseDirectoryID }
     * 
     */
    public CourseDirectoryID createCourseDirectoryID() {
        return new CourseDirectoryID();
    }

    /**
     * Create an instance of {@link MetadataKeywords }
     * 
     */
    public MetadataKeywords createMetadataKeywords() {
        return new MetadataKeywords();
    }

    /**
     * Create an instance of {@link LDCS3 }
     * 
     */
    public LDCS3 createLDCS3() {
        return new LDCS3();
    }

    /**
     * Create an instance of {@link JACS3 }
     * 
     */
    public JACS3 createJACS3() {
        return new JACS3();
    }

}
