//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xcri.co.uk",
xmlns = {
    @XmlNs(namespaceURI = "http://xcri.co.uk", prefix = "courseDataProgramme")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.xcri;

import javax.xml.bind.annotation.XmlNs;

