//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package org.xcri.profiles._1_2.catalog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.purl.net.mlo.AssessmentDType;
import org.purl.net.mlo.ObjectiveDType;
import org.purl.net.mlo.PrerequisiteDType;


/**
 * <p>Java class for commonAndCommonDescriptiveElements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commonAndCommonDescriptiveElements">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xcri.org/profiles/1.2/catalog}commonElements">
 *       &lt;sequence>
 *         &lt;element name="abstract" type="{http://xcri.org/profiles/1.2/catalog}descriptionDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="applicationProcedure" type="{http://xcri.org/profiles/1.2/catalog}descriptionDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}assessment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="learningOutcome" type="{http://xcri.org/profiles/1.2/catalog}descriptionDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}objective" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}prerequisite" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regulations" type="{http://xcri.org/profiles/1.2/catalog}descriptionDType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commonAndCommonDescriptiveElements", propOrder = {
    "_abstract",
    "applicationProcedure",
    "assessment",
    "learningOutcome",
    "objective",
    "prerequisite",
    "regulations"
})
@XmlSeeAlso({
    CourseDType.class,
    PresentationDType.class
})
public class CommonAndCommonDescriptiveElements 
    extends CommonElements implements java.io.Serializable
{

    @XmlElement(name = "abstract")
    protected List<DescriptionDType> _abstract;
    protected List<DescriptionDType> applicationProcedure;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected List<AssessmentDType> assessment;
    protected List<DescriptionDType> learningOutcome;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected List<ObjectiveDType> objective;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected List<PrerequisiteDType> prerequisite;
    protected List<DescriptionDType> regulations;

    /**
     * Gets the value of the abstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionDType }
     * 
     * 
     */
    public List<DescriptionDType> getAbstract() {
        if (_abstract == null) {
            _abstract = new ArrayList<DescriptionDType>();
        }
        return this._abstract;
    }

    /**
     * Gets the value of the applicationProcedure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationProcedure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationProcedure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionDType }
     * 
     * 
     */
    public List<DescriptionDType> getApplicationProcedure() {
        if (applicationProcedure == null) {
            applicationProcedure = new ArrayList<DescriptionDType>();
        }
        return this.applicationProcedure;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssessmentDType }
     * 
     * 
     */
    public List<AssessmentDType> getAssessment() {
        if (assessment == null) {
            assessment = new ArrayList<AssessmentDType>();
        }
        return this.assessment;
    }

    /**
     * Gets the value of the learningOutcome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the learningOutcome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLearningOutcome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionDType }
     * 
     * 
     */
    public List<DescriptionDType> getLearningOutcome() {
        if (learningOutcome == null) {
            learningOutcome = new ArrayList<DescriptionDType>();
        }
        return this.learningOutcome;
    }

    /**
     * Gets the value of the objective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectiveDType }
     * 
     * 
     */
    public List<ObjectiveDType> getObjective() {
        if (objective == null) {
            objective = new ArrayList<ObjectiveDType>();
        }
        return this.objective;
    }

    /**
     * Gets the value of the prerequisite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prerequisite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrerequisite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrerequisiteDType }
     * 
     * 
     */
    public List<PrerequisiteDType> getPrerequisite() {
        if (prerequisite == null) {
            prerequisite = new ArrayList<PrerequisiteDType>();
        }
        return this.prerequisite;
    }

    /**
     * Gets the value of the regulations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regulations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegulations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionDType }
     * 
     * 
     */
    public List<DescriptionDType> getRegulations() {
        if (regulations == null) {
            regulations = new ArrayList<DescriptionDType>();
        }
        return this.regulations;
    }

}
