//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 04:17:50 PM BST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://xcri.org/profiles/1.2/catalog",
xmlns = {
    @XmlNs(namespaceURI = "http://xcri.org/profiles/1.2/catalog", prefix = "")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xcri.profiles._1_2.catalog;

import javax.xml.bind.annotation.XmlNs;
