//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 10:15:17 AM BST 
//


package org.xcri.profiles._1_2.catalog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.purl.dc.elements._1.SimpleLiteral;
import org.purl.net.mlo.DurationDType;
import org.purl.net.mlo.Resource;
import org.purl.net.mlo.StartDType;


/**
 * <p>Java class for presentationDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="presentationDType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xcri.org/profiles/1.2/catalog}commonAndCommonDescriptiveElements">
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.org/net/mlo}start" minOccurs="0"/>
 *         &lt;element name="end" type="{http://xcri.org/profiles/1.2/catalog}temporalDType" minOccurs="0"/>
 *         &lt;element name="startUntil" type="{http://xcri.org/profiles/1.2/catalog}temporalDType" minOccurs="0"/>
 *         &lt;element name="endFrom" type="{http://xcri.org/profiles/1.2/catalog}temporalDType" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}duration" minOccurs="0"/>
 *         &lt;element name="applyFrom" type="{http://xcri.org/profiles/1.2/catalog}temporalDType" minOccurs="0"/>
 *         &lt;element name="applyUntil" type="{http://xcri.org/profiles/1.2/catalog}temporalDType" minOccurs="0"/>
 *         &lt;element name="applyTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}engagement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="studyMode" type="{http://xcri.org/profiles/1.2/catalog}vocabularyDType" minOccurs="0"/>
 *         &lt;element name="attendanceMode" type="{http://xcri.org/profiles/1.2/catalog}vocabularyDType" minOccurs="0"/>
 *         &lt;element name="attendancePattern" type="{http://xcri.org/profiles/1.2/catalog}vocabularyDType" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}languageOfInstruction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="languageOfAssessment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}places" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/net/mlo}cost" minOccurs="0"/>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="venue" type="{http://xcri.org/profiles/1.2/catalog}venueDType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "presentationDType", propOrder = {
    "start",
    "end",
    "startUntil",
    "endFrom",
    "duration",
    "applyFrom",
    "applyUntil",
    "applyTo",
    "engagement",
    "studyMode",
    "attendanceMode",
    "attendancePattern",
    "languageOfInstruction",
    "languageOfAssessment",
    "places",
    "cost",
    "age",
    "venue"
})
public class PresentationDType
    extends CommonAndCommonDescriptiveElements implements java.io.Serializable
{

    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected StartDType start;
    protected TemporalDType end;
    protected TemporalDType startUntil;
    protected TemporalDType endFrom;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected String duration;
    protected TemporalDType applyFrom;
    protected TemporalDType applyUntil;
    protected String applyTo;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected List<SimpleLiteral> engagement;
    protected VocabularyDType studyMode;
    protected VocabularyDType attendanceMode;
    protected VocabularyDType attendancePattern;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected List<SimpleLiteral> languageOfInstruction;
    protected List<String> languageOfAssessment;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected Resource places;
    @XmlElement(namespace = "http://purl.org/net/mlo")
    protected SimpleLiteral cost;
    protected Object age;
    protected List<VenueDType> venue;

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link StartDType }
     *     
     */
    public StartDType getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartDType }
     *     
     */
    public void setStart(StartDType value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalDType }
     *     
     */
    public TemporalDType getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalDType }
     *     
     */
    public void setEnd(TemporalDType value) {
        this.end = value;
    }

    /**
     * Gets the value of the startUntil property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalDType }
     *     
     */
    public TemporalDType getStartUntil() {
        return startUntil;
    }

    /**
     * Sets the value of the startUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalDType }
     *     
     */
    public void setStartUntil(TemporalDType value) {
        this.startUntil = value;
    }

    /**
     * Gets the value of the endFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalDType }
     *     
     */
    public TemporalDType getEndFrom() {
        return endFrom;
    }

    /**
     * Sets the value of the endFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalDType }
     *     
     */
    public void setEndFrom(TemporalDType value) {
        this.endFrom = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationDType }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationDType }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the applyFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalDType }
     *     
     */
    public TemporalDType getApplyFrom() {
        return applyFrom;
    }

    /**
     * Sets the value of the applyFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalDType }
     *     
     */
    public void setApplyFrom(TemporalDType value) {
        this.applyFrom = value;
    }

    /**
     * Gets the value of the applyUntil property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalDType }
     *     
     */
    public TemporalDType getApplyUntil() {
        return applyUntil;
    }

    /**
     * Sets the value of the applyUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalDType }
     *     
     */
    public void setApplyUntil(TemporalDType value) {
        this.applyUntil = value;
    }

    /**
     * Gets the value of the applyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyTo() {
        return applyTo;
    }

    /**
     * Sets the value of the applyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyTo(String value) {
        this.applyTo = value;
    }

    /**
     * Gets the value of the engagement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the engagement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEngagement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getEngagement() {
        if (engagement == null) {
            engagement = new ArrayList<SimpleLiteral>();
        }
        return this.engagement;
    }

    /**
     * Gets the value of the studyMode property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularyDType }
     *     
     */
    public VocabularyDType getStudyMode() {
        return studyMode;
    }

    /**
     * Sets the value of the studyMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularyDType }
     *     
     */
    public void setStudyMode(VocabularyDType value) {
        this.studyMode = value;
    }

    /**
     * Gets the value of the attendanceMode property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularyDType }
     *     
     */
    public VocabularyDType getAttendanceMode() {
        return attendanceMode;
    }

    /**
     * Sets the value of the attendanceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularyDType }
     *     
     */
    public void setAttendanceMode(VocabularyDType value) {
        this.attendanceMode = value;
    }

    /**
     * Gets the value of the attendancePattern property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularyDType }
     *     
     */
    public VocabularyDType getAttendancePattern() {
        return attendancePattern;
    }

    /**
     * Sets the value of the attendancePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularyDType }
     *     
     */
    public void setAttendancePattern(VocabularyDType value) {
        this.attendancePattern = value;
    }

    /**
     * Gets the value of the languageOfInstruction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageOfInstruction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageOfInstruction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getLanguageOfInstruction() {
        if (languageOfInstruction == null) {
            languageOfInstruction = new ArrayList<SimpleLiteral>();
        }
        return this.languageOfInstruction;
    }

    /**
     * Gets the value of the languageOfAssessment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageOfAssessment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageOfAssessment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguageOfAssessment() {
        if (languageOfAssessment == null) {
            languageOfAssessment = new ArrayList<String>();
        }
        return this.languageOfAssessment;
    }

    /**
     * Gets the value of the places property.
     * 
     * @return
     *     possible object is
     *     {@link Resource }
     *     
     */
    public Resource getPlaces() {
        return places;
    }

    /**
     * Sets the value of the places property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource }
     *     
     */
    public void setPlaces(Resource value) {
        this.places = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setCost(SimpleLiteral value) {
        this.cost = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAge(Object value) {
        this.age = value;
    }

    /**
     * Gets the value of the venue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the venue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVenue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VenueDType }
     * 
     * 
     */
    public List<VenueDType> getVenue() {
        if (venue == null) {
            venue = new ArrayList<VenueDType>();
        }
        return this.venue;
    }

}
